# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTAnimation',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'ReactiveCocoa', '2.4.7'
  pod 'AFNetworking', '2.6.1'
  pod 'FMDB', '2.5'
  pod 'MJExtension', '2.5.14'

  target 'DemoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp-tvOS


end
